/** @format */

// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
// export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const LOADING_IDEA_DATA = "LOADING_IDEA_DATA";
// Data reducer types
export const SET_TOPICS = "SET_TOPICS";
export const SET_ORGANIZATION_TYPES = "SET_ORGANIZATION_TYPES";

export const ADD_SCREAMS = "ADD_SCREAMS";
export const SET_SCREAMS = "SET_SCREAMS";
export const SET_SCREAM = "SET_SCREAM";
export const LIKE_SCREAM = "LIKE_SCREAM";
export const UNLIKE_SCREAM = "UNLIKE_SCREAM";
export const VOTED_TRUE = "VOTED_TRUE";
export const VOTED_FALSE = "VOTED_FALSE";

export const DELETE_SCREAM = "DELETE_SCREAM";
export const POST_SCREAM = "POST_SCREAM";

export const EDIT_SCREAM = "EDIT_SCREAM";

export const SUBMIT_COMMENT = "SUBMIT_COMMENT";

export const SET_COMMENTS = "SET_COMMENTS";
export const SET_COMMENT = "SET_COMMENT";

export const DELETE_COMMENT = "DELETE_COMMENT";

export const LOADING_PROJECTS_DATA = "LOADING_PROJECTS_DATA";

export const SET_PROJECTS = "SET_PROJECTS";
export const LOADING_PROJECTROOM_DATA = "LOADING_PROJECTROOM_DATA";
export const SET_PROJECT = "SET_PROJECT";
export const LOADING_PROJECT_SCREAMS = "LOADING_PROJECT_SCREAMS";

export const LOADING_MY_SCREAMS = "LOADING_MY_SCREAMS";
export const SET_MY_SCREAMS = "SET_MY_SCREAMS";

export const SUBMIT_CHAT = "SUBMIT_CHAT";

export const OPEN_SCREAM = "OPEN_SCREAM";
export const CLOSE_SCREAM = "CLOSE_SCREAM";

export const OPEN_PROJECTROOM = "OPEN_PROJECTROOM";
export const CLOSE_PROJECT = "CLOSE_PROJECT";
export const OPEN_CREATE_PROJECTROOM = "OPEN_CREATE_PROJECTROOM";

export const OPEN_ACCOUNT = "OPEN_ACCOUNT";
export const CLOSE_ACCOUNT = "CLOSE_ACCOUNT";
export const LOADING_MYSCREAMS_DATA = "LOADING_MYSCREAMS_DATA";

export const CLEAR_LOADING_ERRORS = "CLEAR_LOADING_ERRORS";

export const SET_SCREAM_USER = "SET_SCREAM_USER";

export const SET_FULL_SCREAMS = "SET_FULL_SCREAMS";

export const OPEN_MONITORING_SCREAM = "OPEN_MONITORING_SCREAM";
export const CLOSE_MONITORING_SCREAM = "CLOSE_MONITORING_SCREAM";

export const SET_COOKIES = "SET_COOKIES";

export const SET_INFOPAGE_CLOSED = "SET_INFOPAGE_CLOSED";
export const SET_INFOPAGE_OPEN = "SET_INFOPAGE_OPEN";

export const SET_MAP_LOADED = "SET_MAP_LOADED";
export const SET_MAP_BOUNDS = "SET_MAP_BOUNDS";
export const SET_INITIAL_MAP_BOUNDS = "SET_INITIAL_MAP_BOUNDS";
export const SET_MAP_VIEWPORT = "SET_MAP_VIEWPORT";
export const SET_INITIAL_MAP_VIEWPORT = "SET_INITIAL_MAP_VIEWPORT";

export const SET_SWIPEPOSITION_UP = "SET_SWIPEPOSITION_UP";
export const SET_SWIPEPOSITION_DOWN = "SET_SWIPEPOSITION_DOWN";

// export const SET_CREATE_PROJECT_FORM_DATA = "SET_CREATE_PROJECT_FORM_DATA";
export const OPEN_CREATE_ORGANIZATION = "OPEN_CREATE_ORGANIZATION";

export const LOADING_ORGANIZATIONS_DATA = "LOADING_ORGANIZATIONS_DATA";
export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";

export const OPEN_ORGANIZATION = "OPEN_ORGANIZATION";
export const SET_ORGANIZATION = "SET_ORGANIZATION";
export const LOADING_ORGANIZATION_DATA = "LOADING_ORGANIZATION_DATA";
